//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boardgame_Category
    {
        public int BoardgameCategory_id { get; set; }
        public Nullable<int> Category_id { get; set; }
        public Nullable<int> Boardgame_id { get; set; }
    
        public virtual Boardgame Boardgame { get; set; }
        public virtual Category Category { get; set; }
    }
}
