//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boardgame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boardgame()
        {
            this.Boardgame_Category = new HashSet<Boardgame_Category>();
            this.Designers = new HashSet<Designer>();
            this.Owners = new HashSet<Owner>();
            this.PlaySessions = new HashSet<PlaySession>();
        }
    
        public int Boardgame_id { get; set; }
        public Nullable<int> Publisher_id { get; set; }
        public string Titel { get; set; }
        public Nullable<int> MinNumberOfPlayers { get; set; }
        public Nullable<int> MaxNumberOfPlayers { get; set; }
        public Nullable<int> MinPlayingTime { get; set; }
        public Nullable<int> MaxPlayingTime { get; set; }
        public Nullable<int> MinAgeToPlay { get; set; }
        public Nullable<int> MaxAgeToPlay { get; set; }
        public Nullable<bool> ContainsSmallParts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boardgame_Category> Boardgame_Category { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Designer> Designers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Owner> Owners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaySession> PlaySessions { get; set; }
    }
}
