//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameClubEntities : DbContext
    {
        public GameClubEntities()
            : base("name=GameClubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boardgame> Boardgames { get; set; }
        public virtual DbSet<Boardgame_Category> Boardgame_Category { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Designer> Designers { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlaySession> PlaySessions { get; set; }
        public virtual DbSet<Publisher> Publishers { get; set; }
    }
}
